# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7742c8f3306ce34d31ebd1d798ee73266a846768445cdfbef5eccfe0678bcb9738a99df32fbd2834ac93561f119633ae289b93db7d8c0ab2a12a7ec3259e1f7

test:
  secret_key_base: 00144c035c6ccce5572f22f312f612c0f9cccde2962d0419b91b601dc8505e334f3b66cc7b41967eee7a86b12dc06dce35c6d4cb24fc5df38a2eb092d2eb3e01

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%=IO.read(File.expand_path('~/.secret_key_base')) rescue ''%>
